minimumReleaseAge: 2880 # 2 days
minimumReleaseAgeExclude: ['react', 'react-dom', 'next', '@next/env']
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1 # https://github.com/pnpm/pnpm/issues/10202 
