name: TypeScript check

on:
  pull_request:

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - shell: bash
        env:
          NEXT_GHOST_API_KEY: ${{ secrets.NEXT_GHOST_API_KEY }}
        run: npm run build && npx tsc --noEmit
