name: Playwright E2E Tests
on:
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@c2d88d3ecc89a9ef08eebf45d9637801dcee7eb5

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
        name: Install pnpm

      - name: Install Node.js
        uses: actions/setup-node@633bb92bc0aabcae06e8ea93b85aecddd374c402
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Installation des dépendances NPM
        run: pnpm install --frozen-lockfile

      - name: Installation des navigateurs Playwright
        run: pnpm exec playwright install --with-deps

      - name: Execution des tests Playwright
        run: pnpm exec playwright test

      - name: Ajout du commentaire dans la PR
        uses: daun/playwright-report-summary@be9e270edd5ad86038604d3caa84a819a6ff6fed
        if: always()
        with:
          report-file: test-results.json
          comment-title: 'Résultats des tests E2E Playwright'

      - name: Mise à disposition des résultats
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        if: always()
        with:
          name: Résultats
          path: playwright-report/
          retention-days: 7
